Parameters:
  HostedZoneName:
    Type: String
    Default: "cuffney.com"
    Description: hosted zone name

  DomainName:
    Type: String
    Default: "cuffney.com"
    Description: domain name (subdomains included)

  SsmNamespace:
    Type: String
    Default: "/cuffney/main/cuffney-com"
    Description: namespace for SSM parameters

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DomainName

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AddPerm
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${OriginAccessIdentity}
            Action: s3:GetObject
            Resource: !Sub arn:aws:s3:::${DomainName}/*

  OriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref DomainName

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt Bucket.RegionalDomainName
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${OriginAccessIdentity}
        Enabled: "true"
        Comment: !Ref DomainName
        DefaultRootObject: index.html
        Aliases:
          - !Ref DomainName
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          Compress: "true"
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: "true"
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_200
        ViewerCertificate:
          AcmCertificateArn: !Ref SslCert
          SslSupportMethod: sni-only
        CustomErrorResponses:
          - ErrorCachingMinTTL: 300
            ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCachingMinTTL: 300
            ErrorCode: 404

  SslCert:
    Type: AWS::CertificateManager::Certificate
    Properties:
      ValidationMethod: DNS
      DomainName:
        Ref: DomainName

  DNSRecord:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName:
        Fn::Sub: "${HostedZoneName}."
      RecordSets:
        - Name:
            Ref: DomainName
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName:
              Fn::GetAtt:
                - Distribution
                - DomainName

  DistributionIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "${SsmNamespace}/distribution/id"
      Type: String
      Value: !Ref Distribution

  # SSM Param for the source bucket name
  # SSM Parameter of the disribution id
  SourceBucketNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "${SsmNamespace}/source-bucket/name"
      Type: String
      Value: !Ref Bucket
